# Site settings
title: "Junteng Liu"
email: "jliugi@connect.ust.hk"
description: "Personal homepage of Junteng Liu - PhD candidate at HKUST NLP Group"
baseurl: "/LJT-Homepage"
url: "https://dhuagome.github.io"
github_username: Vicent0205
twitter_username: junteng88716710
linkedin_username:
orcid: ""
google_scholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
google_analytics:
google_tag:
disqus_shortname:
lang: en

# Author information (used in sidebar)
author:
  name: "Junteng Liu"
  avatar: "images/profile.png"
  bio: "First-year PhD candidate at HKUST NLP Group. Research: NLP & ML."
  email: "jliugi@connect.ust.hk"
  github: Vicent0205
  twitter: junteng88716710
  linkedin:
  googlescholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Hong_Kong

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
